const word_library = {
  English: {
    "DLC includes:": "<p>DLC includes:</p>",
    "Includes:": "Includes:",
    "Base game": "Base game",
    "Digital soundtrack": "Digital soundtrack",
    "Digital artbook": "Digital artbook",
    "[character name] outfit": "[character name] outfit",
    "[character name] skin": "[character name] skin",
    "weapon skin": "weapon skin",
    "3-day Early Access": "3-day Early Access",
    "expansion": "expansion",
    "Season Pass": "Season Pass",
    "[title] pack": "[title] pack",
    "weapon": "weapon",
    "cosmetic items": "cosmetic items",
    "vehicle skin": "vehicle skin",
    "online access": "online access",
    "upgrade": "upgrade"
  },
  Spanish: {
    "DLC includes:": "Incluye:",
    "Includes:": "Incluye:",
    "Base game": "El juego base",
    "Digital soundtrack": "Banda sonora digital",
    "Digital artbook": "Libro de arte digital",
    "[character name] outfit": "[character name] outfit",
    "[character name] skin": "Skin de [character name]",
    "weapon skin": "skin de arma",
    "3-day Early Access": "Acceso temprano de 3 días",
    "expansion": "expansión",
    "[title] pack": "[Título] Pack",
    "weapon": "arma",
    "cosmetic items": "Objetos cosméticos",
    "vehicle skin": "Skin de vehículo",
    "online access": "Acceso en linea"
  },
  Lithuanian: {
    "DLC includes:": "Šis DLC įtraukia:",
    "Includes:": "Įtraukia:",
    "Base game": "pagrindinį žaidimą",
    "Digital soundtrack": "skaitmeninį garso takelį",
    "Digital artbook": "skaitmeninį artbook",
    "[character name] outfit": "[character name] aprangą",
    "[character name] skin": "[character name] skiną",
    "weapon skin": "ginklo skiną",
    "3-day Early Access": "išankstinę x dienų prieigą",
    "expansion": "plėtinį",
    "Season Pass": "sezono pasą",
    "[title] pack": "[title] rinkinį",
    "weapon": "ginklą",
    "cosmetic items": "kosmetiniai priedai",
    "vehicle skin": "transporto priemonės skiną",
    "online access": "prieigą internetu",
    "upgrade": "papildymą"
  },
  French: {
    "DLC includes:": "Le DLC comprend :",
    "Includes:": "Comprend:",
    "Base game": "Le jeu de base",
    "Digital soundtrack": "Bande-son numérique",
    "Digital artbook": "Artbook numérique",
    "[character name] outfit": "Set d'équipement [character name]",
    "[character name] skin": "Skin de [character name]",
    "weapon skin": "skin d'arme",
    "3-day Early Access": "Accès anticipé de 3 jours",
     "expansion": "expansion",
    "Season Pass": "Pass de saison",
    "[title] pack": "pack [title]",
    "weapon": "arme",
    "cosmetic items": "Articles cosmétiques",
    "vehicle skin": "Skin de véhicule",
    "online access": "accès en ligne",
    "upgrade": "amélioration"
  },
  Romanian: {
    "DLC includes:": "DLC-ul include:",
    "Includes:": "Include:",
    "Base game": "Jocul de bază",
    "Digital soundtrack": "Coloană sonoră digitală",
    "Digital artbook": "Cartea de artă digitală",
    "[character name] outfit": "Set d'équipement [character name]",
    "[character name] skin": "Skinul [character name]",
    "weapon skin": "Skinul pentru armă",
    "3-day Early Access": "3 zile Early Access",
    "expansion": "expansiune",
    "Season Pass": "Pasul de sezon",
    "[title] pack": "pack [title]",
    "weapon": "armă",
    "cosmetic items": "Articole cosmetice",
    "vehicle skin": "Skin pentru vehicule",
    "online access": "acces online",
    "upgrade": "Upgrade"
  },
  Polish: {
    "DLC includes:": "DLC zawiera:",
    "Includes:": "Zawiera:",
    "Base game": "Podstawową wersję gry",
    "Digital soundtrack": "Cyfrowa ścieżka dźwiękowa",
    "Digital artbook": "Cyfrowy album z grafikami",
    "[character name] outfit": "Zestaw ze strojem [character name]",
    "[character name] skin": "skórkę do [character name]",
    "weapon skin": "skórki do broni",
    "3-day Early Access": "3-dniowy wczesny dostęp",
    "expansion": "ekspansja",
    "Season Pass": "Przekaz sezonu",
    "[title] pack": "paczkę [title]",
    "weapon": "broń",
    "cosmetic items": "Przedmioty kosmetyczne",
    "vehicle skin": "Skin pojazdu",
    "online access": "dostęp online",
    "upgrade": "aktualizację"
  },
  German: {
    "DLC includes:": "DLC enthält:",
    "Includes:": "Enthält:",
    "Base game": "Das Basisspiel",
    "Digital soundtrack": "Digitaler Soundtrack",
    "Digital artbook": "Digitales Kunstbuch",
    "[character name] outfit": "[character name] Outfit",
    "[character name] skin": "[character name] Skin",
    "weapon skin": "Waffen Skin",
    "3-day Early Access": "3 Tage Early Access",
    "expansion": "Erweiterung",
    "Season Pass": "Saisonkarte",
    "[title] pack": "[title] Pack",
    "weapon": "Waffe",
    "cosmetic items": "Kosmetische Gegenstände",
    "vehicle skin": "Fahrzeug-Skin",
    "online access": "Online-Zugang",
    "upgrade": "Upgrade"
   },
  Portuguese: {
    "DLC includes:": "O DLC inclui:",
    "Includes:": "Inclui:",
    "Base game": "O jogo base",
    "Digital soundtrack": "Trilha sonora digital",
    "Digital artbook": "Artbook digital",
    "[character name] outfit": "Roupa [character name]",
    "[character name] skin": "Skin de [character name]",
    "weapon skin": "Skin de arma",
    "3-day Early Access": "3 dias de Acesso Prévio",
    "expansion": "expansão",
    "Season Pass": "Passe de temporada",
    "[title] pack": "Pacote [title]",
    "weapon": "arma",
    "cosmetic items": "Itens cosméticos",
    "vehicle skin": "Skin de veículo",
    "online access": "acesso online",
    "upgrade": "Upgrade"
  },
  Dutch: {
    "DLC includes:": "DLC bevat:",
    "Includes:": "Bevat:",
    "Base game": "De basis game",
    "Digital soundtrack": "Digitale soundtrack",
    "Digital artbook": "Digitaal artbook",
    "[character name] outfit": "[character name] outfit",
    "[character name] skin": "[character name] skin",
    "weapon skin": "weapon skin",
    "3-day Early Access": "3-day Early Access",
    "expansion": "uitbreiding",
    "Season Pass": "Seizoenspas",
    "[title] pack": "[title] pack",
    "weapon": "wapen",
    "cosmetic items": "Cosmetische items",
    "vehicle skin": "Voertuig skin",
    "online access": "online toegang",
    "upgrade": "upgrade"
  },
  Greek: {
    "DLC includes:": "Το Πρόσθετο Περιεχόμενο περιλαμβάνει:",
    "Includes:": "Περιλαμβάνει:",
    "Base game": "Το βασικό παιχνίδι",
    "Digital soundtrack": "Ψηφιακό soundtrack",
    "Digital artbook": "Ψηφιακό βιβλίο τέχνης",
    "[character name] outfit": "Στολή του [character name]",
    "[character name] skin": "Στολή [character name]",
    "weapon skin": "Εμφάνιση όπλου",
    "3-day Early Access": "Πρόσβαση 3 ημέρες νωρίτερα",
    "expansion": "επέκταση",
    "Season Pass": "Εποχιακό πάσο",
    "[title] pack": "Πακέτο [title]",
    "weapon": "όπλο",
    "cosmetic items": "Διακοσμητικά αντικείμενα",
    "vehicle skin": "Εμφάνιση οχήματος",
    "online access": "online πρόσβαση",
    "upgrade": "Αναβάθμιση"
    },
};